name: 'Dependent PR check'
description: 'Checks if current PR has any opened dependent PRs'

inputs:
  dependent-pr:
    description: 'PR which this PR is dependent on'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      with:
        script: |
          const success = `PR #${${{ inputs.dependent-pr }}} has been merged. PR dependency check passed.`
          const failure = `PR #${${{ inputs.dependent-pr }}} has yet to be merged. PR dependency check failed.`
          let conclusion = 'success'
          let output = {
            title: 'Dependent PR check',
            summary: success 
          }
          try {
            const response = await github.rest.pulls.checkIfMerged({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.dependent-pr }}
            })
            if (response.status == 204) {
              console.log(success)
            } else {
              throw Error(response.status)
            }
          } catch {     
              console.log(failure)
              conclusion = 'failure'
              output.summary = failure
          }
          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "Dependent PR check",
            head_sha: context.sha,
            status: 'completed',
            conclusion: conclusion,
            output: output
          })
