name: 'Dependent PR check'
description: 'Checks if current PR has any opened dependent PRs'

inputs:
  dependent-pr:
    description: 'PR which this PR is dependent on'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      with:
        script: |
          try {
            const response = await github.rest.pulls.checkIfMerged({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.dependent-pr }}
            })
            if (response.status == 204) {
              console.log(`PR #${${{ inputs.dependent-pr }}} has been merged. PR dependency check passed.`)
            } else {
              throw Error(response.status)
            }
          } catch {     
              core.setFailed(`PR #${${{ inputs.dependent-pr }}} has yet to be merged. PR dependency check failed.`)
          }
