name: 'Dependent PR check'
description: 'Checks if current PR has any opened dependent PRs'

inputs:
  dependent-pr:
    description: 'PR which this PR is dependent on'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      with:
        script: |
          const response = github.rest.pulls.checkIfMerged({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ inputs.dependent-pr }}
          })
          if (response.ok) {
            console.log(`PR #${${{ inputs.dependent-pr }}} has been merged. Dependency check passed.`)
          } else {
            console.error(`PR #${${{ inputs.dependent-pr }}} has yet to be merged. Dependency check failed.`)
          }
          return response
